### ISSUE TITLE
Windows Phone 8.1

### ISSUE THREAD

**Issue by aasavad** [christocracy/cordova-plugin-background-fetch#16]
Hi,

Is there any way to implement this on Apache Cordova Windows 8.1 Project?

**Comment by christocracy** [comment]
"Background fetch" is a concept introduced by ios7.  I'm not aware of any
other platform implementation.

On Wednesday, April 15, 2015, aasavad <notifications@github.com> wrote:

> Hi,
>
> Is there any way to implement this on Apache Cordova Windows 8.1 Project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/16>
> .
>


-- 
Snet from Gmail Mobile

**Comment by aasavad** [comment]
Thank you Chris.
