### ISSUE TITLE
[IOS 8.3] BackgroundFetch not working

### ISSUE THREAD

**Issue by apollon0815** [christocracy/cordova-plugin-background-fetch#17]
Thank you for the wonderful plugin.

Today i updated my enviroment platform to the newest xode version with IOS 8.3. As i tested my app everything works fine, but when i simulate the background fetch i get this error

<code>CFNetwork internal error (0xc01a:/SourceCache/CFNetwork_Sim/CFNetwork-711.3.18/Connection/URLConnectionClient.cpp:513)
</code>

i simplyfied my code for the background fetch to the following

<code> 
var Fetcher = window.plugins.backgroundFetch;
var fetchCallback = function()
{  
 console.log('BackgroundFetch initiated');
  Fetcher.finish();
}
Fetcher.configure(fetchCallback);
</code>

the error is the same.

I hope you can fix it as soon as possible.

**Comment by christocracy** [comment]
My code had nothing to do with URLConnectionClient

On Friday, April 17, 2015, apollon0815 <notifications@github.com> wrote:

> Thank you for the wonderful plugin.
>
> Today i updated my enviroment platform to the newest xode version with IOS
> 8.3. As i tested my app everything works fine, but when i simulate the
> background fetch i get this error
>
> CFNetwork internal error
> (0xc01a:/SourceCache/CFNetwork_Sim/CFNetwork-711.3.18/Connection/URLConnectionClient.cpp:513)
>
> i simplyfied my code for the background fetch to the following
>
>
> var Fetcher = window.plugins.backgroundFetch;
> var fetchCallback = function()
> {
>
> console.log('BackgroundFetch initiated');
> Fetcher.finish();
> }
> Fetcher.configure(fetchCallback);
>
> the error is the same.
>
> I hope you can fix it as soon as possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17>
> .
>


-- 
Snet from Gmail Mobile

**Comment by apollon0815** [comment]
hi thank you for your fast answer. i know, but the background fetch is empty like you see. and i get the error just when i simulate the background fetch. i also get this error and the error from the first post

<code>
Can't endBackgroundTask: no background task exists with identifier 32, or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
</code>

on ios 8.1 everything works fine

**Comment by apollon0815** [comment]
have you test the background fetch under ios 8.3?

**Comment by christocracy** [comment]
I tested it just now with 8.3 on a simple test-app and it works without any
issue.  I would suggest you do the same, test it in a HelloWorld cordova
app, isolated from your application code.



On Fri, Apr 17, 2015 at 7:00 AM, apollon0815 <notifications@github.com>
wrote:

> have you test the background fetch under ios 8.3?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-93965038>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by apollon0815** [comment]
okay, thank you for you effort. i will test it and write if it works

**Comment by christocracy** [comment]
You can also try the branch #scrap_timer.  I haven’t touched this plugin in
ages but there’s some unnecessary use of Timers which have been removed.

https://github.com/christocracy/cordova-plugin-background-fetch/tree/scrap_timer

Cordova CLI allows you to install a branch by appending #branch-name to
plugin url.

$ cordova plugin add https://plugin/name.git*#some-branch*



On Fri, Apr 17, 2015 at 7:29 AM, apollon0815 <notifications@github.com>
wrote:

> okay, thank you for you effort. i will test it and write if it works
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-93968912>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by apollon0815** [comment]
hi christocracy,

i installed the plugin with the helloworld test-app. no errors. i think ios 8.3 does handle ajax requests in the background fetch on a other way.

but the plugn is not working. i can just read "CDVBackgroundFetch configure". when i simulate the fetch nothing is happend. it is the same problem like here: http://beauty98star.blogspot.de/2015/04/ios-background-fetch-not-working-even.html

can you find a solution?

**Comment by christocracy** [comment]
Check UIBackgroundModes includes key "fetch"

On Saturday, April 18, 2015, apollon0815 <notifications@github.com> wrote:

> hi christocracy,
>
> i installed the plugin with the helloworld test-app. no errors. i think
> ios 8.3 does handle ajax requests in the background fetch on a other way.
>
> but the plugn is not working. i can just read "CDVBackgroundFetch
> configure". when i simulate the fetch nothing is happend. it is the same
> problem like here:
> http://beauty98star.blogspot.de/2015/04/ios-background-fetch-not-working-even.html
>
> can you find a solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-94176354>
> .
>


-- 
Snet from Gmail Mobile

**Comment by apollon0815** [comment]
I checked this. This app worked fine on older xcode with ios 8.1 sdk. With the new version of xcode and and 8.3 sdk background fetch don't start.

**Comment by apollon0815** [comment]
Can you upload your test-app i would like to test it under my enviroment. I used cordova 3.1.0, because the compatibility with other plugins. Camn this be the problem?

**Comment by apollon0815** [comment]
https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html

"General
.....
The Xcode menu command Simulator Background Fetch does not work."

**Comment by szuzul** [comment]
How can I simulate Background Fetch in the real app . with Fetch.start()  somewhere in the code or ?

My use case is to fetch data on push notification and refresh localstorage in background with fetched data, but without opening the app is that possible with this plugin ?

**Comment by christocracy** [comment]
That's not what this plugin is for.   You misunderstand the "iOS Background
Fetch" mechanism.  You have no control *when* a fetch event occurs--it's
purely up to Apple, but in practice, about every 15min during prime time
hours (less frequently during sleep hours.

You simulate Fetch in XCode via Debug menu.

And anyway, iOS is capable of awakening your app in bg to receive a push,
providing 30s of bg running.

That's what I created this:
https://github.com/christocracy/cordova-plugin-background-notification


On Tuesday, June 16, 2015, szuzul <notifications@github.com> wrote:

> How can I simulate Background Fetch in the real app . with Fetch.start()
> somewhere in the code or ?
>
> My use case is to fetch data on push notification and refresh localstorage
> in background with fetched data, but without opening the app is that
> possible with this plugin ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-112406146>
> .
>


-- 
Snet from Gmail Mobile

**Comment by szuzul** [comment]
Thanks a lot with quick explanation and hint, I think this is what I need, but I'll need to reorder it a little bit to hook it on the angular cycle. Is window object fully accessible in callback function ?

**Comment by christocracy** [comment]
window object, of course.

On Tue, Jun 16, 2015 at 9:35 AM, szuzul <notifications@github.com> wrote:

> Thanks a lot with quick explanation and hint, I think this is what I need,
> but I'll need to reorder it a little bit to hook it on the angular cycle.
> Is window object fully accessible in callback function ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-112431971>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by szuzul** [comment]
Well it seams that both solutions isn't what i'm looking for. In each of the cases reaction of the plugin came after I click on the notification (local or push), but not on the event when notification has arrived on device. But anyway thanks for clearing me paths.

**Comment by christocracy** [comment]
I guess you just ignored the very important NOTE in the
background-notification README:

*NOTE* Your push notification message must contain the key
"content-available": 1
If you don't do supply that APNS-only key, iOS won't awake your app to send
the push to it.

It's up to you to have your server and/or Push vendor send that key in your
notification.  I cannot help you with that

On Wednesday, June 17, 2015, szuzul <notifications@github.com> wrote:

> Well it seams that both solutions isn't what i'm looking for. In each of
> the cases reaction of the plugin came after I click on the notification
> (local or push), but not on the event when notification has arrived on
> device. But anyway thanks for clearing me paths.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-112780323>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Read more about content-available here at Apple

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

On Wednesday, June 17, 2015, Chris Scott <christocracy@gmail.com> wrote:

> I guess you just ignored the very important NOTE in the
> background-notification README:
>
> *NOTE* Your push notification message must contain the key
> "content-available": 1
> If you don't do supply that APNS-only key, iOS won't awake your app to
> send the push to it.
>
> It's up to you to have your server and/or Push vendor send that key in
> your notification.  I cannot help you with that
>
> On Wednesday, June 17, 2015, szuzul <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Well it seams that both solutions isn't what i'm looking for. In each of
>> the cases reaction of the plugin came after I click on the notification
>> (local or push), but not on the event when notification has arrived on
>> device. But anyway thanks for clearing me paths.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-112780323>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by szuzul** [comment]
It works now when the app is in the backgorund mode, content-avalable helps, but I also include  : 
 <key>UIBackgroundModes</key>
    <array>
        <string>remote-notification</string>
    </array>
in plist file. 
I found interesting discussion on https://github.com/phonegap-build/PushPlugin/issues/288
Still when I kill the app and web-view is down, I can't fetch data in background.  This suits for me just fine. Thanks for the instructions.

**Comment by christocracy** [comment]
My background-notification plugin auto-adds
<https://github.com/christocracy/cordova-plugin-background-notification/blob/master/plugin.xml#L25>
that key to the .plist



On Wed, Jun 17, 2015 at 9:56 AM, szuzul <notifications@github.com> wrote:

> It works now when the app is in the backgorund mode, content-avalable
> helps, but I also include :
> UIBackgroundModes
>
> remote-notification
>
> in plist file.
> I found interesting discussion on phonegap-build/PushPlugin#288
> <https://github.com/phonegap-build/PushPlugin/issues/288>
> Still when I kill the app and web-view is down, I can't fetch data in
> background. This suits for me just fine. Thanks for the instructions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/17#issuecomment-112810273>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by szuzul** [comment]
Maybe is something wrong with my cordova or in xcode build process, I'm pretty sure I added it manually. Anyway it works like charm :+1:
