### ISSUE TITLE
completion handler was never called but my test code is correct

### ISSUE THREAD

**Issue by lakano** [christocracy/cordova-plugin-background-fetch#21]
Hi @christocracy !

I just installed your last commit on the plugin, but I received this error:
```
- CDVBackgroundFetch onFetch
[1310:648320] Warning: Application delegate received call to application:performFetchWithCompletionHandler: but the completion handler was never called.
```

But, this doesn't seems to be my code, just look the simple code please:
```
            BackgroundFetch.configure(function() {
                console.log('$$$$$$$$$$$$$$$$$$$$$ FETCH $$$$$$$$$$$$$$$$$$');
                BackgroundFetch.finish();
            }, function() {
                console.log( '############# ERROR BgFetch ############');
            }, { stopOnTerminate: true });
```

My console logs messages doesn't appears. I also tried to remove the console.log() message but it's the same error.

I also tested to change your new option stopOnTerminate to false, the error is still here.

May be a new bug?

Thanks for your help!
Regards

EDIT: I precise I call this after the onDeviceReady event was fired.

**Comment by christocracy** [comment]
Cannot duplicate this issue.  There is no bug.

**Comment by Pixelartdev** [comment]
Is not true I also get the bug. In my case I needed to use areal device, because the simulator hasn't any problem, but my real device is giving the exact same failure. I tried also different solutions provided here, but the are not really working
