### ISSUE TITLE
'Cordova/CDVJSON.h' file not found in CDVBackgroundFetch.m on Archive step

### ISSUE THREAD

**Issue by davixz** [christocracy/cordova-plugin-background-fetch#27]
Hi chris,

Thank you for great plugin.

Im having a strange issue here, only when im trying to archive/export the project.
When i just install the app in simulator or phone (iphone 4 here) it builds and works fine.
The error is: 'Cordova/CDVJSON.h' file not found   in CDVBackgroundFetch.m
Ive atached a screen shot with more details.

Im using cordova 6.0.0, ios-deploy 1.8.5, cordova ios 4.0.0, the background-fech plugin is v 2.0.4, my xcode is 7.0 and target deployment is IOS 7.0.

Sorry to bother you but im really lost here.

Thank you again!

![cdv_background_fetch](https://cloud.githubusercontent.com/assets/4032656/13226857/6b2c81e0-d972-11e5-8ea5-8af27e62e779.png)

**Comment by davixz** [comment]
Hi!

Just found out that i had to use cordova 3.9.2, looked into cordova ios in that version and the file was in CordovaLib folder, in 4.0.0 the structure of the folder is different.

**Comment by christocracy** [comment]
I haven't been using this plugin for a while.  Feel free to fix it and
issue a pull-request.

Perhaps one of the forks has figured out a solution already.

On Thu, Feb 25, 2016 at 8:53 AM, David Azevedo <notifications@github.com>
wrote:

> Hi!
>
> Just found out that i had to use cordova 3.9.2, looked into cordova ios in
> that version and the file was in CordovaLib folder, in 4.0.0 the structure
> of the folder is different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/27#issuecomment-188791933>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by davixz** [comment]
Thank you for take the time to come here Chris
