### ISSUE TITLE
issue with fetch callback

### ISSUE THREAD

**Issue by ashlesha86** [christocracy/cordova-plugin-background-fetch#31]
Hello, I am trying to run the plugin with a sample code. In device ready event, in fetcallback function i just run a loop for 100 times and print the value on console. and called fetcher.finish. When i simulate the background fetch from xcode, it printed on console as
CDVBackgroundFetch configure
CDVBackgroundFetch  onFetch
CDVBackgroundFetch finiish
CDVBackgroundFetch stopBackgroundTask.
  The code was not executed.
  Can u please suggest?
Thanks.

**Comment by christocracy** [comment]
Printing it once isn't enough?  Are you sure you don't have an error in
your JavaScript?

On Thursday, March 31, 2016, ashlesha86 <notifications@github.com> wrote:

> Hello, I am trying to run the plugin with a sample code. In device ready
> event, in fetcallback function i just run a loop for 100 times and print
> the value on console. and called fetcher.finish. When i simulate the
> background fetch from xcode, it printed on console as
> CDVBackgroundFetch configure
> CDVBackgroundFetch onFetch
> CDVBackgroundFetch finiish
> CDVBackgroundFetch stopBackgroundTask.
> The code was not executed.
> Can u please suggest?
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/31>
>


-- 
Snet form Gmail Mobile

**Comment by ashlesha86** [comment]
Here is my test code.
var fetchCallback=function()
{
console. log('BackgroundFetch initiated ');
for(i=0; i<100; i++)
{
console.log('test');
}
Fetcher.Finish();
}
i did not even got the message-BackgroundFetch initiated on the console. only what i get is CDVBackgroundFetch configure
CDVBackgroundFetch onFetch
CDVBackgroundFetch finiish
CDVBackgroundFetch stopBackgroundTask. along with datetime

**Comment by hevatix** [comment]
I have the same problem...  :(...

**Comment by christocracy** [comment]
Are you using the latest version?  it works perfectly for me.

**Comment by hevatix** [comment]
What is the last version?
I have 2.0.2 from pgb
![image](https://cloud.githubusercontent.com/assets/13125950/15024496/ba57c82c-11fa-11e6-9518-24e6fce59c78.png)

**Comment by christocracy** [comment]
Why don't you look on npm?
https://www.npmjs.com/package/cordova-plugin-background-fetch

**Comment by hevatix** [comment]
Thankyou
Now... I have 3.0.4 version...
![image](https://cloud.githubusercontent.com/assets/13125950/15025187/b024da5e-11fd-11e6-97bc-adbe66948c92.png)
But phonegap recommend:
![image](https://cloud.githubusercontent.com/assets/13125950/15025332/5b73631c-11fe-11e6-98f7-932762a21a36.png)
But it still doesn´t work

**Comment by christocracy** [comment]
How are you testing this?

On Wed, May 4, 2016 at 3:11 PM, hevatix <notifications@github.com> wrote:

> Thankyou
> Now... I have 3.0.4 version...
> [image: image]
> <https://cloud.githubusercontent.com/assets/13125950/15025187/b024da5e-11fd-11e6-97bc-adbe66948c92.png>
> But phonegap recommend:
> [image: image]
> <https://cloud.githubusercontent.com/assets/13125950/15025332/5b73631c-11fe-11e6-98f7-932762a21a36.png>
> But it still doesn´t work
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/31#issuecomment-216970244>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by hevatix** [comment]
Waiting for the event...
for each event I just send a log for testing. But I would like make an ajax and modify a contact

**Comment by christocracy** [comment]
Are you not aware that you can simulate a background fetch event with Xcode?

On Wednesday, May 4, 2016, hevatix <notifications@github.com> wrote:

> Waiting for the event...
> for each event I just send a log for testing. But I would like make an
> ajax and modify a contact
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/31#issuecomment-216985823>
>


-- 
Snet form Gmail Mobile

**Comment by hevatix** [comment]
But I´m deloping in Windows with phonegap. Do I need a MAC?  or what can I do?
Or I didn´t understand you...
This is my code to test
![image](https://cloud.githubusercontent.com/assets/13125950/15027621/535f941e-120a-11e6-8a57-a5065237ace3.png)

**Comment by christocracy** [comment]
You Windows people...yes, if you're serious about iOS dev, you should have
a Mac.

Why are you executing #configure twice??  And once without any params???

On Wednesday, May 4, 2016, hevatix <notifications@github.com> wrote:

> But I´m deloping in Windows with phonegap. Do I need a MAC? or what can I
> do?
> Or I didn´t understand you...
> This is my code to test
> [image: image]
> <https://cloud.githubusercontent.com/assets/13125950/15027621/535f941e-120a-11e6-8a57-a5065237ace3.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/31#issuecomment-216990132>
>


-- 
Snet form Gmail Mobile

**Comment by hevatix** [comment]
I just forgot that line... 
Yes I know, but My company wants an app really quick, and I have problems with a background mode with Apple... 
But please tell me What should I do?

**Comment by hevatix** [comment]
it´s done.... It works.
Thankyou :+1:

**Comment by christocracy** [comment]
What was the problem?

On Thu, May 5, 2016 at 11:29 AM, hevatix <notifications@github.com> wrote:

> it´s done.... It works.
> Thankyou [image: :+1:]
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/31#issuecomment-217186476>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by hevatix** [comment]
I don´t now... It just works now!!!

**Comment by vahidreza** [comment]
@christocracy 
hi
you mentioned earlier that we can simulate a background fetch event with Xcode.
can you point me toward a tutorial or guide for doing so for my cordova app?

**Comment by christocracy** [comment]
1. With app already running:
![](https://www.dropbox.com/s/vll1mztb7csnwcy/Screenshot%202016-05-23%2012.29.35.png?dl=1)

2.  Launch due to background-fetch event
![](https://www.dropbox.com/s/v4fcpw5ecw9bpj8/Screenshot%202016-05-23%2012.30.22.png?dl=1)
