### ISSUE TITLE
Is it possible to use this plugin for android ?

### ISSUE THREAD

**Issue by Jpsankaran** [christocracy/cordova-plugin-background-fetch#32]
Hi,
Is it possible to use this plugin for _android_ ?
Or any other plugins that needs to be support both **Android & IOS**.

**Comment by christocracy** [comment]
This is an iOS only mechanism introduced in iOS 7.  Android does not have a
concept of "background fetch"

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:performFetchWithCompletionHandler
:

On Monday, May 23, 2016, Jpsankaran <notifications@github.com> wrote:

> Hi,
> Is it possible to use this plugin for *android* ?
> Or any other plugins that needs to be support both *Android & IOS*.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/32>
>


-- 
Snet form Gmail Mobile

**Comment by Jpsankaran** [comment]
Ok thanks.

Any other chance to get geo location, even app is not open?

**Comment by christocracy** [comment]
Yes, use my Cordova-background-Geolocation plugin (which includes this
fetch plugin as a dependency)

http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium

On Monday, May 23, 2016, Jpsankaran <notifications@github.com> wrote:

> Ok thanks.
>
> Any other chance to get geo location, even app is not open?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-fetch/issues/32#issuecomment-220980838>
>


-- 
Snet form Gmail Mobile
